### ISSUE TITLE
rollup:umd error

### ISSUE THREAD

**Issue by dking3876** [jvandemo/generator-angular2-library#187]
My build server is throwing an error with all the defaults saying that moduleName is an unexpected key for rollup

Starting 'rollup:umd'...
options.entry is deprecated, use options.input
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (C:\projects\daedelus\src\Daedelus.Projects.Services.Angular\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:171:11)
    at checkInputOptions (C:\projects\daedelus\src\Daedelus.Projects.Services.Angular\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:10154:14)
    at Object.rollup (C:\projects\daedelus\src\Daedelus.Projects.Services.Angular\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:10225:3)
    at C:\projects\daedelus\src\Daedelus.Projects.Services.Angular\node_modules\gulp-rollup\index.js:149:23
    at Array.map (native)
    at C:\projects\daedelus\src\Daedelus.Projects.Services.Angular\node_modules\gulp-rollup\index.js:138:37
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm ERR! code ELIFECYCLE

**Comment by apeter10** [comment]
Please refer to [this](https://github.com/jvandemo/generator-angular2-library/issues/186) issue.

**Comment by abalad** [comment]
+1

**Comment by dking3876** [comment]
That does appear to have worked..
