### ISSUE TITLE
npm run build command fails

### ISSUE THREAD

**Issue by geoffrey-gaurav** [jvandemo/generator-angular2-library#191]
admin1@PC-131:/home1/lamppp/htdocs/test$ npm run build

> nethues-charts@0.1.0 build /home1/lamppp/htdocs/test
> gulp build

[11:36:00] Using gulpfile /home1/lamppp/htdocs/test/gulpfile.js
[11:36:00] Starting 'clean:dist'...
[11:36:00] Starting 'clean:tmp'...
[11:36:00] Starting 'clean:build'...
[11:36:00] Starting 'compile'...
[11:36:00] Finished 'compile' after 1.51 ms
[11:36:00] Finished 'clean:dist' after 15 ms
[11:36:00] Starting 'copy:source'...
[11:36:00] Finished 'clean:tmp' after 23 ms
[11:36:00] Finished 'clean:build' after 21 ms
[11:36:00] Starting 'clean'...
[11:36:00] Finished 'clean' after 7.17 μs
[11:36:00] Starting 'build'...
[11:36:00] Finished 'build' after 1.87 μs
[11:36:00] Finished 'copy:source' after 184 ms
[11:36:00] Starting 'inline-resources'...
[11:36:00] Finished 'inline-resources' after 9.14 ms
[11:36:00] Starting 'ngc'...
[11:36:02] Finished 'ngc' after 1.65 s
[11:36:02] Starting 'rollup:fesm'...
options.entry is deprecated, use options.input
[11:36:02] Finished 'rollup:fesm' after 466 ms
[11:36:02] Starting 'rollup:umd'...
options.entry is deprecated, use options.input

**events.js:160
      throw er; // Unhandled 'error' event
      ^**
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/home1/lamppp/htdocs/test/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/home1/lamppp/htdocs/test/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10154:14)
    at Object.rollup (/home1/lamppp/htdocs/test/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10225:3)
    at /home1/lamppp/htdocs/test/node_modules/gulp-rollup/index.js:149:23
    at Array.map (native)
    at /home1/lamppp/htdocs/test/node_modules/gulp-rollup/index.js:138:37
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nethues-charts@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nethues-charts@0.1.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nethues-charts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nethues-charts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nethues-charts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/lamppp/htdocs/test/npm-debug.log

##### version

admin1@PC-131:/home1/lamppp/htdocs/test$ **yo** --version
**2.0.0**
admin1@PC-131:/home1/lamppp/htdocs/test$ **npm** --version
**3.10.8**

######## yo doctor
admin1@PC-131:/home1/lamppp/htdocs/test$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

**Comment by Bosje** [comment]
The problem seems to reside in the latest version of gulp-rollup or rollup package. I "fixed" the problem by change the caret ^ to a tilde ~ for gulp-rollup in package.json.
`"gulp-rollup": "~2.11.0",`

**Comment by geoffrey-gaurav** [comment]
Thanks it works...

**Comment by jvandemo** [comment]
Thank you, version 11.4.0 has been released with a fix (see #190) 👍
