### ISSUE TITLE
I can not install lib

### ISSUE THREAD

**Issue by enough1987** [jvandemo/generator-angular2-library#20]
I did librely, than I published it, but I can not install what i did.
Does generator work? 

```
npm install hope --save

> node-zopfli@1.4.0 install S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "S:\\Sources\\Applications\\prototype\\platform\\resource-management\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=S:\\Sources\\Applications\\prototype\\platform\\resource-management\\app\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=S:\\Sources\\Applications\\prototype\\platform\\resource-management\\app\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "S:\\Sources\\Applications\\prototype\\platform\\resource-management\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
project-name@0.0.0 S:\Sources\Applications\prototype\platform\resource-management\app
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
`-- hope@1.0.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```

**Comment by jvandemo** [comment]
@enough1987 &mdash; There is a similar issue [here](https://github.com/AngularClass/angular2-webpack-starter/issues/626), where they recommend to run:

```bash
$ npm install --no-optional
```

Can you try that? Thanks!

**Comment by enough1987** [comment]
I used this - 
` npm install emosewa --save --no-optional`

and 
this - 
` npm install emosewa --no-optional`

emosewa -s name og lib ( reversed awesome ) 

> 
> > emosewa@0.1.5 postinstall S:\Sources\Applications\prototype\platform\resource-management\app\node_modules\emosewa
> > typings install
> 
> typings WARN deprecated 2016-09-15: "registry:dt/angular-protractor#1.5.0+20160425143459" is deprecated (updated, replaced or removed)
> typings WARN deprecated 2016-06-02: "registry:dt/es6-shim#0.31.2+20160317120654" is deprecated (updated, replaced or removed)
> typings WARN deprecated 2016-10-03: "registry:dt/jasmine#2.2.0+20160412134438" is deprecated (updated, replaced or removed)
> typings WARN deprecated 2016-09-15: "registry:dt/selenium-webdriver#2.44.0+20160317120654" is deprecated (updated, replaced or removed)
> 
> +-- es6-shim (global)
> +-- angular-protractor (global dev)
> +-- jasmine (global dev)
> `-- selenium-webdriver (global dev)
> 
> project-name@0.0.0 S:\Sources\Applications\prototype\platform\resource-management\app
> +-- UNMET PEER DEPENDENCY @angular/common@2.0.0
> +-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
> +-- UNMET PEER DEPENDENCY @angular/core@2.0.0
> +-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
> `-- emosewa@0.1.5
> 
> npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
> npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
> npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
> npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
> npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
> npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
>

**Comment by enough1987** [comment]
I work, but I do not know what helped )
`npm install -g node-pre-gyp
`
or
`npm install emosewa --save --no-optional`

**Comment by jvandemo** [comment]
@enough1987 &mdash; Thank you for the update.

I will close this issue for now. If you think it is specifically related to this generator, please don't hesitate to re-open it.

Thanks again!
