### ISSUE TITLE
linting fails

### ISSUE THREAD

**Issue by w4lt-dev** [jvandemo/generator-angular2-library#203]
Generated a new library and getting follewed linting errors:
```
Error: Error at playground/index.ts:9:31: Cannot find module 'testlib'.
Error at src/sample.component.spec.ts:7:1: Cannot find name 'describe'.
Error at src/sample.component.spec.ts:14:3: Cannot find name 'beforeEach'.
Error at src/sample.component.spec.ts:28:3: Cannot find name 'it'.
Error at src/sample.component.spec.ts:29:5: Cannot find name 'expect'.
```
After i changed the `tsconfig.json` 
removed:
`"types": []`
added:
```
"typeRoots": [
  "node_modules/@types"
]
```
I am still getting 
`Error: Error at playground/index.ts:9:31: Cannot find module 'testlib'.`

**Comment by izifortune** [comment]
@w4lt-dev  that's normal because this is mapped through systemjs, have a look at system.config.js

**Comment by jvandemo** [comment]
@w4lt-dev &mdash; Can you let us know if you were able to fix it using `system.config.js`?

@izifortune &mdash; Thank you for your help!

**Comment by w4lt-dev** [comment]
@jvandemo To get rid of the linting error I changed the tsconfigs a bit.

./tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "rootDir": "./src",
    "lib": [
      "es2015",
      "dom"
    ],
    "skipLibCheck": true,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "playground"
  ]
}
```
./playground/tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "../.playground",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "paths": {
      "testlib": ["../dist/index.d.ts"]
    }
  }
}
```
./package.json
```
"lint:lib": "tslint --type-check --project tsconfig.json",
"lint": "npm run lint:lib && npm run playground:lint",
"playground:lint": "npm run build && tslint --type-check --project playground/tsconfig.json",
```
To lint the playground the library must be build to get the type definition from the library. This removes the `Cannot find module` error.

Now the linting works and returns:
`playground/index.ts[12, 13]: The selector of the component "AppComponent" should be named kebab-case and include dash (https://goo.gl/mBg67Z)`

an easier warning to fix :smiley:
