### ISSUE TITLE
npm run playground fails

### ISSUE THREAD

**Issue by ShermanT** [jvandemo/generator-angular2-library#206]
`admin1@PC-131:/home1/lamppp/htdocs/angular-charts$npm run playground

> angular-charts@0.1.0 playground /home1/lamppp/htdocs/angular-charts
> concurrently "npm run build:watch" "npm run playground:build" "npm run lite"

[1] 
[1] > angular-charts@0.1.0 playground:build /home1/lamppp/htdocs/angular-charts
[1] > tsc -p playground -w
[1] 
[2] 
[2] > angular-charts@0.1.0 lite /home1/lamppp/htdocs/angular-charts
[2] > lite-server
[2] 
[0] 
[0] > angular-charts@0.1.0 build:watch /home1/lamppp/htdocs/angular-charts
[0] > gulp
[0] 
[1] playground/index.ts(9,31): error TS2307: Cannot find module 'angular-charts'.
[1] 3:09:36 PM - Compilation complete. Watching for file changes.
[1] 
[1] 
[2] ** browser-sync config **
[2] { injectChanges: false,
[2]   files: [ './**/*.{html,htm,css,js}' ],
[2]   watchOptions: { ignored: 'node_modules' },
[2]   server: 
[2]    { baseDir: 'src',
[2]      middleware: [ [Function], [Function] ],
[2]      routes: 
[2]       { '/': 'playground',
[2]         '/node_modules/': 'node_modules',
[2]         '/dist/': 'dist',
[2]         '/.playground': '.playground' } } }
[2] [Browsersync] Access URLs:
[2]  --------------------------------------
[2]        Local: http://localhost:3000
[2]     External: http://192.168.1.189:3000
[2]  --------------------------------------
[2]           UI: http://localhost:3001
[2]  UI External: http://192.168.1.189:3001
[2]  --------------------------------------
[2] [Browsersync] Serving files from: src
[2] [Browsersync] Watching files...
[2] 17.09.22 15:09:41 200 GET /index.html
[0] [15:09:41] 
[0] Using gulpfile /home1/lamppp/htdocs/angular-charts/gulpfile.js
[0] [15:09:41] 
[0] Starting 'clean:dist'...
[0] [15:09:41] 
[0] Starting 'clean:tmp'...
[0] [15:09:41] 
[0] Starting 'clean:build'...
[0] [15:09:41] 
[0] Starting 'compile'...
[0] [15:09:41] 
[0] Starting 'watch'...
[0] [15:09:41] Finished 'watch' after 22 ms
[0] [15:09:41] Finished 'compile' after 26 ms
[0] [15:09:41] Finished 'clean:tmp' after 37 ms
[0] [15:09:41] Finished 'clean:build' after 35 ms
[0] [15:09:41] Finished 'clean:dist' after 160 ms
[0] [15:09:41] Starting 'copy:source'...
[0] [15:09:41] 
[0] Starting 'clean'...
[0] [15:09:41] Finished 'clean' after 3.71 μs
[0] [15:09:41] Starting 'build'...
[0] [15:09:41] Finished 'build' after 2.43 μs
[0] [15:09:41] Starting 'build:watch'...
[0] [15:09:41] Finished 'build:watch' after 2.23 μs
[0] [15:09:41] Starting 'default'...
[0] [15:09:41] Finished 'default' after 7.45 μs
[0] [15:09:41] 
[0] Finished 'copy:source' after 56 ms
[0] [15:09:41] Starting 'inline-resources'...
[0] [15:09:41] 
[0] Finished 'inline-resources' after 13 ms
[0] [15:09:41] Starting 'ngc'...
[2] [Browsersync] Reloading Browsers...
[2] [Browsersync] Reloading Browsers...
[2] 17.09.22 15:09:42 304 GET /core-js/client/shim.min.js
[2] 17.09.22 15:09:42 304 GET /zone.js/dist/zone.js
[2] 17.09.22 15:09:42 200 GET /systemjs.config.js
[2] 17.09.22 15:09:42 304 GET /systemjs/dist/system.src.js
[2] 17.09.22 15:09:43 200 GET /index.js
[2] 17.09.22 15:09:43 304 GET /@angular/platform-browser/bundles/platform-browser.umd.js
[2] 17.09.22 15:09:43 304 GET /@angular/core/bundles/core.umd.js
[2] 17.09.22 15:09:43 304 GET /@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
[2] 17.09.22 15:09:43 404 GET /dist/angular-charts.umd.js
[2] 17.09.22 15:09:43 404 GET /sockjs-node/info
[2] events.js:160
[2]       throw er; // Unhandled 'error' event
[2]       ^
[2] 
[2] Error: watch build ENOSPC
[2]     at exports._errnoException (util.js:1026:11)
[2]     at FSWatcher.start (fs.js:1429:19)
[2]     at Object.fs.watch (fs.js:1456:11)
[2]     at createFsWatchInstance (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[2]     at setFsWatchListener (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[2]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[2]     at FSWatcher.NodeFsHandler._handleDir (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:407:19)
[2]     at FSWatcher.<anonymous> (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:455:19)
[2]     at FSWatcher.<anonymous> (/home1/lamppp/htdocs/angular-charts/node_modules/chokidar/lib/nodefs-handler.js:460:16)
[2]     at FSReqWrap.oncomplete (fs.js:123:15)
[2] 
[2] npm
[2]  ERR! Linux 4.4.0-93-generic
[2] npm ERR!
[2]  
[2] argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lite"
[2] npm ERR! node v6.8.1
[2] npm ERR! npm  v3.10.8
[2] npm ERR! code ELIFECYCLE
[2] npm ERR! angular-charts@0.1.0 lite: `lite-server`
[2] npm ERR! Exit status 1
[2] npm ERR! 
[2] npm ERR! Failed at the angular-charts@0.1.0 lite script 'lite-server'.
[2] npm ERR! Make sure you have the latest version of node.js and npm installed.
[2] npm ERR! If you do, this is most likely a problem with the angular-charts package,
[2] npm ERR! not with npm itself.
[2] npm ERR! Tell the author that this fails on your system:
[2] npm ERR!     lite-server
[2] npm ERR! You can get information on how to open an issue for this project with:
[2] npm ERR!     npm bugs angular-charts
[2] npm ERR! Or if that isn't available, you can get their info via:
[2] npm ERR!     npm owner ls angular-charts
[2] npm ERR! There is likely additional logging output above.
[0] [15:09:44] Finished 'ngc' after 2.36 s
[0] [15:09:44] Starting 'rollup:fesm'...
[2] 
[2] npm ERR! Please include the following file with any support request:
[2] npm ERR!     /home1/lamppp/htdocs/angular-charts/npm-debug.log
[2] npm run lite exited with code 1
[0] [15:09:44] 
[0] Finished 'rollup:fesm' after 331 ms
[0] [15:09:44] 
[0] Starting 'rollup:umd'...
[0] No name was provided for external module '@angular/core' in options.globals – guessing 'core'
[0] No name was provided for external module '@angular/common' in options.globals – guessing 'common'
[0] [15:09:44] 
[0] Finished 'rollup:umd' after 52 ms
[0] [15:09:44] 
[0] Starting 'copy:build'...
[0] [15:09:44] 
[0] Finished 'copy:build' after 13 ms
[0] [15:09:44] 
[0] Starting 'copy:manifest'...
[0] [15:09:44] 
[0] Finished 'copy:manifest' after 7.94 ms
[0] [15:09:44] 
[0] Starting 'copy:readme'...
[0] [15:09:44] 
[0] Finished 'copy:readme' after 1.73 ms
[0] [15:09:44] 
[0] Starting 'clean:build'...
[0] [15:09:44] 
[0] Finished 'clean:build' after 6.61 ms
[0] [15:09:44] 
[0] Starting 'clean:tmp'...
[0] [15:09:44] 
[0] Finished 'clean:tmp' after 3.73 ms
[0] Compilation finished succesfully
`

**Comment by Kamilius** [comment]
@ShermanT please wrap your output into `code block`, because this is barealy readable https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by ShermanT** [comment]
thanks done

>  Playground works only occasionally, I've managed to get it working only once. And mostly it is an infinite refresh loop for me.

### any solution for this

**Comment by izifortune** [comment]
@ShermanT  looking at the error quickly it seems there's no more space. Please have a look here
https://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by jvandemo** [comment]
@ShermanT &mdash; Can you please verify whether you have disk space left, see comment by @izifortune.

@izifortune &mdash; Thank you for your help!

**Comment by ShermanT** [comment]
@jvandemo I doesn't think so
 
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           385M  6.0M  379M   2% /run
/dev/sda1        37G   11G   24G  31% /
tmpfs           1.9G   93M  1.8G   5% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda5        15G  503M   14G   4% /boot
/dev/sda7        46G  1.6G   42G   4% /opt
/dev/sda9       172G  3.7G  159G   3% /home
/dev/sda6       7.3G   18M  6.9G   1% /tmp
/dev/sda10      176G   55G  113G  33% /home1
tmpfs           385M   60K  385M   1% /run/user/1000
```

**Comment by IckleChris** [comment]
I can confirm the same issue - fresh install, ran `npm run build` followed by `npm run playground` and returns;

```
[1] playground/index.ts(9,30): error TS2307: Cannot find module 'my-module'.
[1] 1:23:51 PM - Compilation complete. Watching for file changes.
```

**Comment by dgroh** [comment]
+1 

Playground used to work. As soon as I delete the `.playground` folder and run `npm run playground` I get `404` for the module js file:

>[0] Finished 'clean:build' after 14 ms
[0] [10:48:53] Starting 'clean:tmp'...
[2] [Browsersync] Reloading Browsers...
[2] [Browsersync] Reloading Browsers...
[2] 17.11.20 10:48:53 404 GET /.playground/index.js <<<<<<<<HERE<<<<<<<<<<<<<
[0] [10:48:53]
[0] Finished 'clean:tmp' after 106 ms

**Comment by Ismaestro** [comment]
+1, any updates?

**Comment by kenji-1996** [comment]
+1, ran into this on setup just not and confused as to why there is this issue:
`playground/index.ts(9,31): error TS2307: Cannot find module 'techgorilla-ui'.`

**Comment by radomeit** [comment]
+1
I got the same  404 GET /.playground/index.js error.

After changing playground/index.html line 16 to:
    System.import('.playground/playground/index.js').catch(function(err){ console.error(err); });

and running cmd.exe as admin as described above, it sometimes works - meaning i have to start the server several times until it doesn't throw an error. The error is:
[2] events.js:160
[2]       throw er; // Unhandled 'error' event
[2]       ^
[2]
[2] Error: EPERM: operation not permitted, lstat '...myapp\build'
[2]     at Error (native)
[2]
[2] npm ERR! Windows_NT 10.0.15063
[2] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lite"
[2] npm ERR! node v6.12.3
[2] npm ERR! npm  v3.10.10

**Comment by tonysamperi** [comment]
Any news on this?? I cant do an npm publish every time I have to check if everything's fine!!

**Comment by doudbanks** [comment]
Something new guys ?

**Comment by tonysamperi** [comment]
This generator is a generator of the past.

With my generator you'll test your libs with an ordinary `ng serve` Angular 5 6 and 7 supported!
https://github.com/tonysamperi/generator-ngx-lib

**Comment by doudbanks** [comment]
Thanks Tony, I'm trying your generator, I have some issues right at the first npm run build. Could we talk ?

**Comment by tonysamperi** [comment]
@doudbanks sure you can open an issue on my repo!

**Comment by doudbanks** [comment]
Thanks man,

Could I ask you some questions ?

Le mer. 13 févr. 2019 à 09:15, Tony Samperi <notifications@github.com> a
écrit :
