### ISSUE TITLE
 Angular compiler option "flatModuleIndex" requires one and only one .ts file in the "files" field

### ISSUE THREAD

**Issue by dgroh** [jvandemo/generator-angular2-library#249]
since angular-cli 1.6.0 I get the following error:

Thing is I don't really know if it's an angular-cli problem. it was working a few days ago without any change. Out build server started to fail.

The error occurs in the `ngc` task:

> 2017-12-14T15:07:43.7558989Z [16:07:43] 'ngc' errored after 466 ms
2017-12-14T15:07:43.7558989Z [16:07:43] Error: ngc compilation failed: : Angular compiler option "flatModuleIndex" requires one and only one .ts file in the "files" field.
2017-12-14T15:07:43.7558989Z 
2017-12-14T15:07:43.7558989Z     at ngc (D:\Agents\Build1\_work\23\s\my-dnn\gulpfile.js:54:13)
2017-12-14T15:07:43.7558989Z     at reportErrorsAndExit (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\@angular\compiler-cli\src\main.js:126:9)
2017-12-14T15:07:43.7558989Z     at main (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\@angular\compiler-cli\src\main.js:30:12)
2017-12-14T15:07:43.7558989Z     at Gulp.<anonymous> (D:\Agents\Build1\_work\23\s\my-dnn\gulpfile.js:52:10)
2017-12-14T15:07:43.7558989Z     at module.exports (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\orchestrator\lib\runTask.js:34:7)
2017-12-14T15:07:43.7558989Z     at Gulp.Orchestrator._runTask (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\orchestrator\index.js:273:3)
2017-12-14T15:07:43.7558989Z     at Gulp.Orchestrator._runStep (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\orchestrator\index.js:214:10)
2017-12-14T15:07:43.7558989Z     at Gulp.Orchestrator.start (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\orchestrator\index.js:134:8)
2017-12-14T15:07:43.7558989Z     at runNextSet (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\run-sequence\index.js:123:15)
2017-12-14T15:07:43.7558989Z     at Gulp.onTaskEnd (D:\Agents\Build1\_work\23\s\my-dnn\node_modules\run-sequence\index.js:101:4)
2017-12-14T15:07:43.7558989Z ERROR: ngc compilation failed: : Angular compiler option "flatModuleIndex" requires one and only one .ts file in the "files" field.
2017-12-14T15:07:43.7558989Z 
2017-12-14T15:07:43.7871492Z ##[error]Gulp failed with error: C:\Program Files\nodejs\node.exe failed with return code: 1
2017-12-14T15:07:43.7871492Z ##[section]Finishing: [my-dnn] generate dist

**Comment by caroso1222** [comment]
can you please post here some repro steps? also, how does your `src/tsconfig.es5.json` look like?
