### ISSUE TITLE
gulp error after upgrading to nodejs v10.x and npm v6.4.0

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [jvandemo/generator-angular2-library#300]
> @cognitec/http-request-indicator@0.1.0 build /build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/packages/@cognitec/http-request-indicator
> gulp build

gulp[17785]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [gulp]
 2: 0x8938b5 [gulp]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xaff5e8 [gulp]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x2a7108d841bd
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @cognitec/http-request-indicator@0.1.0 build: `gulp build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the @cognitec/http-request-indicator@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brower/.npm/_logs/2018-08-24T10_20_04_456Z-debug.log
(node:17654) UnhandledPromiseRejectionWarning: Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:603:11)
    at execSync (child_process.js:640:13)
    at buildCallback (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build-package.js:103:5)
    at buildPackage (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build-package.js:151:13)
    at build.buildPackages.forEach.package (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build.js:259:48)
    at Array.forEach (<anonymous>)
    at buildPackages (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build.js:259:29)
    at menu5Callback (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build.js:249:5)
    at menu.then.item (/build/brower/gitrepos/FaceVACS-VideoScan-WA-Development/src/build/build.js:214:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

We are unable to upgrade to Angular 6.

**Comment by broweratcognitecdotcom** [comment]
node-sass is extremely problematic in our linux environment. the hours or days we have spent sorting out node-sass problems is incredible. is there no other alternative to this?
